version: '3'

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_HOST=${N8N_HOST:-localhost}
      - NODE_ENV=production
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-manta_n8n_key}
      - WEBHOOK_URL=http://${N8N_HOST:-localhost}:5678/
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./workflows:/home/node/.n8n/workflows
    restart: unless-stopped
    networks:
      - manta-network

networks:
  manta-network:
    driver: bridge